### ISSUE TITLE
Wrong default light theme values

### ISSUE THREAD

**Issue by gabrieltempass** [streamlit/docs#1057]
### Summary

The [Theming](https://docs.streamlit.io/develop/concepts/configuration/theming) page in the docs has this section:

> The following config options show the default Streamlit Light theme recreated in the [theme] section of a .streamlit/config.toml file.

But some default values shown in the recreated `.streamlit/config.toml` file are wrong. More specifically, the values for `primaryColor` and `textColor`. The correct values are those set in the [themeColors.ts](https://github.com/streamlit/streamlit/blob/develop/frontend/lib/src/theme/emotionLightTheme/themeColors.ts) file, that come from [colors.ts](https://github.com/streamlit/streamlit/blob/develop/frontend/lib/src/theme/primitives/colors.ts).

**Expected behavior:**

``` toml
[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
```

**Actual behavior:**

``` toml
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
```
